# Build the images, then run the containers
version: '3.1'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    build: ./backend
    ports:
      - "5432:5432"
    # no need for a persistent volume
    # because we populate the database each time
    #volumes:
    #  - ./backend/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # adminer:
  #   image: adminer
  #   ports:
  #     - "8081:8080"
  # Don't need an admin panel anymore